name = "rss-feed-bot"
main = "index.js"
compatibility_date = "2024-02-04"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["*/15 * * * *"]

[[kv_namespaces]]
binding = "DB"
id = "TODO_REPLACE_WITH_YOUR_KV_ID"
preview_id = "TODO_REPLACE_WITH_YOUR_KV_PREVIEW_ID"
